// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL is not set. Add it in Vercel → Project Settings → Environment Variables (Production, Preview, Development)."
  );
}

// Prisma Migrate requires DIRECT connection — Neon pooler (-pooler) does not support advisory locks.
// Convert pooled URL to direct: ep-xxx-pooler.region... → ep-xxx.region...
const migrateUrl =
  process.env["DIRECT_DATABASE_URL"] ||
  (databaseUrl.includes("-pooler.") ? databaseUrl.replace("-pooler.", ".") : databaseUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    url: migrateUrl,
  },
});
